package org.techuni.TechUniInviteSystem.db.mapper.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.techuni.TechUniInviteSystem.db.entity.base.InviteDiscordJoinedUser;
import org.techuni.TechUniInviteSystem.db.entity.base.InviteDiscordJoinedUserExample;

@Mapper
public interface InviteDiscordJoinedUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    long countByExample(InviteDiscordJoinedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int deleteByExample(InviteDiscordJoinedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int insert(InviteDiscordJoinedUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int insertSelective(InviteDiscordJoinedUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    List<InviteDiscordJoinedUser> selectByExample(InviteDiscordJoinedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    InviteDiscordJoinedUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") InviteDiscordJoinedUser row, @Param("example") InviteDiscordJoinedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") InviteDiscordJoinedUser row, @Param("example") InviteDiscordJoinedUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InviteDiscordJoinedUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_joined_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InviteDiscordJoinedUser row);
}