package org.techuni.TechUniInviteSystem.db.mapper.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.techuni.TechUniInviteSystem.db.entity.base.InviteDiscordState;
import org.techuni.TechUniInviteSystem.db.entity.base.InviteDiscordStateExample;

@Mapper
public interface InviteDiscordStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    long countByExample(InviteDiscordStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int deleteByExample(InviteDiscordStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int insert(InviteDiscordState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int insertSelective(InviteDiscordState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    List<InviteDiscordState> selectByExample(InviteDiscordStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    InviteDiscordState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") InviteDiscordState row, @Param("example") InviteDiscordStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") InviteDiscordState row, @Param("example") InviteDiscordStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InviteDiscordState row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InviteDiscordState row);
}