package org.techuni.TechUniInviteSystem.db.mapper.base;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.techuni.TechUniInviteSystem.db.entity.base.TargetApp;
import org.techuni.TechUniInviteSystem.db.entity.base.TargetAppExample;

@Mapper
public interface TargetAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    long countByExample(TargetAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int deleteByExample(TargetAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int insert(TargetApp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int insertSelective(TargetApp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    List<TargetApp> selectByExample(TargetAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    TargetApp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TargetApp row, @Param("example") TargetAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TargetApp row, @Param("example") TargetAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TargetApp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_app
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TargetApp row);
}