package org.techuni.TechUniInviteSystem.db.entity.base;

import java.time.LocalDateTime;

public class InviteDiscordState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord_state.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord_state.invite_id
     *
     * @mbg.generated
     */
    private Integer inviteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord_state.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord_state.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord_state.id
     *
     * @return the value of invite_discord_state.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord_state.id
     *
     * @param id the value for invite_discord_state.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord_state.invite_id
     *
     * @return the value of invite_discord_state.invite_id
     *
     * @mbg.generated
     */
    public Integer getInviteId() {
        return inviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord_state.invite_id
     *
     * @param inviteId the value for invite_discord_state.invite_id
     *
     * @mbg.generated
     */
    public void setInviteId(Integer inviteId) {
        this.inviteId = inviteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord_state.state
     *
     * @return the value of invite_discord_state.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord_state.state
     *
     * @param state the value for invite_discord_state.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord_state.created_at
     *
     * @return the value of invite_discord_state.created_at
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord_state.created_at
     *
     * @param createdAt the value for invite_discord_state.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InviteDiscordState other = (InviteDiscordState) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInviteId() == null ? other.getInviteId() == null : this.getInviteId().equals(other.getInviteId()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord_state
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInviteId() == null) ? 0 : getInviteId().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        return result;
    }
}