package org.techuni.TechUniInviteSystem.db.entity.base;

import java.time.LocalDateTime;

public class Invite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.search_id
     *
     * @mbg.generated
     */
    private String searchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.is_disabled
     *
     * @mbg.generated
     */
    private Boolean isDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.target_app_id
     *
     * @mbg.generated
     */
    private Integer targetAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite.expires_at
     *
     * @mbg.generated
     */
    private LocalDateTime expiresAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.id
     *
     * @return the value of invite.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.id
     *
     * @param id the value for invite.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.code
     *
     * @return the value of invite.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.code
     *
     * @param code the value for invite.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.search_id
     *
     * @return the value of invite.search_id
     *
     * @mbg.generated
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.search_id
     *
     * @param searchId the value for invite.search_id
     *
     * @mbg.generated
     */
    public void setSearchId(String searchId) {
        this.searchId = searchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.is_disabled
     *
     * @return the value of invite.is_disabled
     *
     * @mbg.generated
     */
    public Boolean getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.is_disabled
     *
     * @param isDisabled the value for invite.is_disabled
     *
     * @mbg.generated
     */
    public void setIsDisabled(Boolean isDisabled) {
        this.isDisabled = isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.target_app_id
     *
     * @return the value of invite.target_app_id
     *
     * @mbg.generated
     */
    public Integer getTargetAppId() {
        return targetAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.target_app_id
     *
     * @param targetAppId the value for invite.target_app_id
     *
     * @mbg.generated
     */
    public void setTargetAppId(Integer targetAppId) {
        this.targetAppId = targetAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite.expires_at
     *
     * @return the value of invite.expires_at
     *
     * @mbg.generated
     */
    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite.expires_at
     *
     * @param expiresAt the value for invite.expires_at
     *
     * @mbg.generated
     */
    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Invite other = (Invite) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getSearchId() == null ? other.getSearchId() == null : this.getSearchId().equals(other.getSearchId()))
            && (this.getIsDisabled() == null ? other.getIsDisabled() == null : this.getIsDisabled().equals(other.getIsDisabled()))
            && (this.getTargetAppId() == null ? other.getTargetAppId() == null : this.getTargetAppId().equals(other.getTargetAppId()))
            && (this.getExpiresAt() == null ? other.getExpiresAt() == null : this.getExpiresAt().equals(other.getExpiresAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getSearchId() == null) ? 0 : getSearchId().hashCode());
        result = prime * result + ((getIsDisabled() == null) ? 0 : getIsDisabled().hashCode());
        result = prime * result + ((getTargetAppId() == null) ? 0 : getTargetAppId().hashCode());
        result = prime * result + ((getExpiresAt() == null) ? 0 : getExpiresAt().hashCode());
        return result;
    }
}