package org.techuni.TechUniInviteSystem.db.entity.base;

public class InviteDiscord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invite_discord.guild_id
     *
     * @mbg.generated
     */
    private Long guildId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord.id
     *
     * @return the value of invite_discord.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord.id
     *
     * @param id the value for invite_discord.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invite_discord.guild_id
     *
     * @return the value of invite_discord.guild_id
     *
     * @mbg.generated
     */
    public Long getGuildId() {
        return guildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invite_discord.guild_id
     *
     * @param guildId the value for invite_discord.guild_id
     *
     * @mbg.generated
     */
    public void setGuildId(Long guildId) {
        this.guildId = guildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InviteDiscord other = (InviteDiscord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGuildId() == null ? other.getGuildId() == null : this.getGuildId().equals(other.getGuildId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invite_discord
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGuildId() == null) ? 0 : getGuildId().hashCode());
        return result;
    }
}