/*
 GRANT SELECT, INSERT, CREATE, ALTER ON DB.target_app TO DBUSER;
 GRANT SELECT, INSERT, UPDATE, CREATE, REFERENCES, ALTER ON DB.invite TO DBUSER;
 GRANT SELECT, INSERT, UPDATE, CREATE, REFERENCES, ALTER ON DB.flyway_schema_history TO DBUSER;

 GRANT SELECT, INSERT, CREATE, ALTER ON DB_dev.target_app TO DBUSER;
 GRANT SELECT, INSERT, UPDATE, CREATE, REFERENCES, ALTER ON DB_dev.invite TO DBUSER;
 GRANT SELECT, INSERT, UPDATE, CREATE, REFERENCES, ALTER ON DB_dev.flyway_schema_history TO DBUSER_dev;
 */

INSERT INTO target_app (name) VALUES ('discord');

CREATE TABLE invite_discord (
    id INT PRIMARY KEY,
    guild_id BIGINT UNSIGNED NOT NULL,

    FOREIGN KEY (id) REFERENCES invite(id)
);